### ISSUE TITLE
Actual state?

### ISSUE THREAD

**Issue by nilskuhn** [golangdaddy/multichain-client#10]
Hi there,
I would like to know about the actual state of this project.
I am developing a go application at the moment (for some weeks at least), accessing MultiChain and I will need some of the  functionalities, this lib provides.
But I would like to improve and extend some things. Obviously there isn't to much going on here since 2018. Does it make sense to work together on this repo or should I go with a fork?
Thanks for an answer, regards,
Nils

**Comment by golangdaddy** [comment]
Its upto you, I'm happy to work together.

**Comment by nilskuhn** [comment]
Me too :)
So than please take a look to my PR's.

**Comment by nilskuhn** [comment]
Thanks for the quick merge. 

Would you consider to add me as a collaborator directly to this repository?
I would still open merge requests for all the changes I am doing, for sure. But it would be a bit simpler than working with a fork.

**Comment by golangdaddy** [comment]
Sure, I tried to add you already. I couldn't find you using account name or
email

**Comment by nilskuhn** [comment]
Hi Alexander, 

that is strange, username `nilskuhn` and email nils.kuhn@iteratec.de should work. I have just added our new email nils.kuhn@iteratec.com and made it the primary one, but that shouldn't change anything.

At the moment I am not able to push a branch:
```
$ git remote -v
origin  git@github.com:iteratec/multichain-client.git (fetch)
origin  git@github.com:iteratec/multichain-client.git (push)
upstream        git@github.com:golangdaddy/multichain-client.git (fetch)
upstream        git@github.com:golangdaddy/multichain-client.git (push)

$ git push upstream
ERROR: Permission to golangdaddy/multichain-client.git denied to nilskuhn.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Could you please try again to add me as a colaborator?

Thanks, Nils

**Comment by golangdaddy** [comment]
it seemed to have worked

**Comment by nilskuhn** [comment]
yes, thanks.
